### ISSUE TITLE
"Keytool" accidental capitalization

### ISSUE THREAD

**Issue by justinmc** [googlecodelabs/photos-sharing#1]
In the command given in step 4 to get the SHA-1, the command is given as `Keytool` with a capital K, but the correct command should have a lowercase k.

Step 4: https://codelabs.developers.google.com/codelabs/google-photos-sharing/index.html?index=..%2F..io2019#3

**Comment by jfschmakeit** [comment]
Good catch! I just fixed this and republished the codelab.
Cheers!

**Comment by justinmc** [comment]
Thanks!
