### ISSUE TITLE
Sing in error

### ISSUE THREAD

**Issue by dominiksr** [googlecodelabs/photos-sharing#11]
The problem arose:

PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)

I was able to solve it with enable the Google Sign-in method in the Authentication tab in Firebase console.

I found the solution here:
https://stackoverflow.com/a/56488089/11754194

**Comment by jfschmakeit** [comment]
Thanks for linking to the solution, that's something that we hadn't encountered before. I have added this as a recommendation to a new "troubleshooting sign in" section in step 4, in case anyone else runs into this.
