### ISSUE TITLE
The screenshot is wrong.

### ISSUE THREAD

**Issue by eungikim** [googlecodelabs/photos-sharing#13]
There explain that google-service.json file should be placed under "android/app/" on page google-photos-sharing/#3.

![](https://codelabs.developers.google.com/codelabs/google-photos-sharing/img/53b0376ad2b003d.png)

But screenshot seems to be placed under "android/app/src/".

**Comment by eungikim** [comment]
#3 linked to closed issue, but, it's https://codelabs.developers.google.com/codelabs/google-photos-sharing/#3.

**Comment by jfschmakeit** [comment]
Thanks for flagging this, I have updated this step to remove the screenshot for now. The correct location is indeed `android/app`.
