### ISSUE TITLE
No Gradle sync

### ISSUE THREAD

**Issue by ciprianprohozescu** [googlecodelabs/photos-sharing#17]
Step 4 mentions that after altering the .gradle scripts, a "sync Gradle..." yellow bar should appear. That does not happen. Furthermore, the "sync Gradle" button seems to be missing both from the toolbar and from the File menu.

**Comment by jfschmakeit** [comment]
I can't find these instructions in this codelab (see https://codelabs.developers.google.com/codelabs/google-photos-sharing ). Which step are you referring to?

There should be no need to edit the gradle configuration as part of this codelab - everything should already be set up for you.
