### ISSUE TITLE
Warning: Your app isn't using AndroidX.

### ISSUE THREAD

**Issue by jfschmakeit** [googlecodelabs/photos-sharing#18]
The Android code of the app needs to be refactored to use AndroidX.

More background in this guide:  https://goo.gl/CP92wY

**Comment by windcloak** [comment]
I tried to do Refactor > Migrate to AndroidX on Android Studio, but I got the error "No Usages Found in the Project"
![image](https://user-images.githubusercontent.com/40670609/77188848-a1cd7980-6aa4-11ea-8b82-ecf3618eab7e.png)

**Comment by jfschmakeit** [comment]
We have a fix for this ready and should be pushing out an update to the codelab next week. Please stay tuned!

**Comment by jfschmakeit** [comment]
The codelab has been upgraded to use Android X in commit cc909390da5385648fc77a19dbbdf3ff984f3b20. 

The warning and prompt to upgrade to Android X should no longer appear.
