### ISSUE TITLE
Uploading photo issue

### ISSUE THREAD

**Issue by SusannaJung** [googlecodelabs/photos-sharing#19]
When I click Add Photo
and then Upload photo
It does not show image selector but shows an error that camera is not available.
![image](https://user-images.githubusercontent.com/45944322/76716754-b8a66000-6774-11ea-8ae8-c5202600b717.png)

**Comment by jfschmakeit** [comment]
Are you running the application in the iOS simulator?
It is not possible to access the camera in the simulator - you will need to run the application on a physical iOS device. We have added a note at the beginning of the codelab to call this out.

(Also see https://help.apple.com/simulator/mac/current/#/devb0244142d under "Hardware differences".)

If you do wish to run this codelab in the iOS simulator, you need to change the call  in the file`contribute_photo_dialog.dart` to the [`image_picker` package](https://pub.dev/packages/image_picker) to use the device gallery (`ImageSource.gallery`) instead.
