### ISSUE TITLE
User that joined can't upload image

### ISSUE THREAD

**Issue by calvinleonardi** [googlecodelabs/photos-sharing#20]
Hi what do I need to add so joined user can upload image on that album too?

**Comment by calvinleonardi** [comment]
help please ?

**Comment by jfschmakeit** [comment]
Is the second user able to see the trips (or albums) that the first user has created? Are you using the same google services configuration to run the app for both users? 

The application is set up so that users authenticate the same application for their Google Photos library, which means that when you have completed the codelab (after step 9), users that have joined the album using the shareToken will also be able to upload media into the same album. 

Are you receiving an error when completing this step?

**Comment by calvinleonardi** [comment]
![Annotation 2020-04-29 145044](https://user-images.githubusercontent.com/60661539/80572663-dc71ec80-8a28-11ea-95e8-24cc06ac481c.jpg)

Yes the second user can see the album that first user created 
I got no error on that but i think this is the problem 
what is 'isCollaborative': instance.isCollaborative, ? 
because when I see on my google photos album, the album that I created using the app isn't collaborative that means only the first user can upload photo and second user cannot

I have tried to make the collaborative true but the album on google photos still not become collaborative
![Annotation 2020-04-29 145536](https://user-images.githubusercontent.com/60661539/80573062-82255b80-8a29-11ea-8444-6cec912482f0.jpg)

**Comment by calvinleonardi** [comment]
![Annotation 2020-04-29 145657](https://user-images.githubusercontent.com/60661539/80573182-b567ea80-8a29-11ea-9be2-610ea594b399.jpg)

on the google photos documentation it says "True if the shared album allows collaborators (users who have joined the album) to add media items to it. "
but i have changed it and it still do nothing

**Comment by calvinleonardi** [comment]
hello anybody here?

**Comment by jfschmakeit** [comment]
This seems to be a bug in the codelab - the `sharedAlbumOptions` aren't set when the album is shared. The default values are used instead, which means that `isCollaborative` is false. Others can join the album, but they won't be able to contribute and add photos. 

This requires some additional work (namely the call in `photos_library_api_client#shareAlbum(..)` needs to be updated to support specifying the `sharedAlbumOptions` in the body of the request as described here: https://developers.google.com/photos/library/guides/share-media#sharing-album )

**Comment by jfschmakeit** [comment]
Closing the loop here - this has been fixed as part of the migration of this codelab to the `flutter/codelabs` repository. See https://github.com/flutter/codelabs/commit/19ece981729f5b8952dcfd13d0eea977c6293ce5
