### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by PedroRTomas** [googlecodelabs/photos-sharing#21]
Hello
Today, I've done:
git clone https://github.com/googlecodelabs/photos-sharing.git
cd photos-sharing
flutter run
And the output was:
![error_flutter](https://user-images.githubusercontent.com/48090914/79250554-b4a25680-7e76-11ea-848d-2e97c4c49992.JPG)
![error_flutter_dependencies](https://user-images.githubusercontent.com/48090914/79250558-b53aed00-7e76-11ea-9f04-dd84c1a846c3.JPG)

I have already read some issues with similar problems and I've tried to update the dependencies versions accordingly.
The issue seems to be related to the management of images. Any advice?

**Comment by vibejain** [comment]
Even the same happened to me.
This code lab must be labelled depreciated.

**Comment by jfschmakeit** [comment]
Thanks for filing the issue - we'll take a look. 
(It looks like there's a versioning issue with the dependencies.)

**Comment by white-hat-vaibhs** [comment]
Hello sir have you checked the dependencies issuess?

**Comment by vibejain** [comment]
> 
> 
> Thanks for filing the issue - we'll take a look.
> (It looks like there's a versioning issue with the dependencies.)
Hello sir have you checked the dependencies issuess?

**Comment by jfschmakeit** [comment]
We have a fix for this ready and should be pushing out an update to the codelab next week. Please stay tuned!

**Comment by jfschmakeit** [comment]
This has been fixed in  80f5e2da1c2de7f06d0a414473bf64beda11b789. 

Please reopen if you are still seeing this issue.
