### ISSUE TITLE
App taking too long to run

### ISSUE THREAD

**Issue by steviehines** [googlecodelabs/photos-sharing#27]
After cloning the code and getting all the packages, the app wont run. Stuck at ''Running Gradle task 'assembleDebug'...''
What are the possible reasons for this please?

**Comment by jfschmakeit** [comment]
How are you running the application? Did you import it into Android Studio?

A few more questions:
What are your Android Studio and Flutter versions? Does the output from running `flutter doctor` identify any issues?
Are there any other log or error messages? This task could take a few minutes (or longer if it's the first time you are building the app) - but it should complete eventually.
