### ISSUE TITLE
Google SignIn Error

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [googlecodelabs/photos-sharing#7]
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null). I found this errors . Please help me how can I solve this?

**Comment by squillace91** [comment]
mine is saying **restricted_client**. 403 error when trying to log in.. saying I haven't configured Oauth consent, but it has been configured just like the codelabs says

**Comment by jfschmakeit** [comment]
This error usually indicates an issue with your Google Developers project or Google Sign-In configuration.

Did you visit the [OAuth consent screen](https://console.developers.google.com/apis/credentials/consent) and add your email address **and** the Library API scopes? (The email address is required at this step.) You will also need to select an email address for "support" on this screen. Make sure to select 'save' before continuing. 

Also make sure that you are configuring access for the same Developers project that you used with Firebase in the earlier step to download the `google-services.json`.

This error could also indicate that you have not set up the SHA-1 signing key for your certificate correctly. You should double check that the package name and the signing certificate SHA-1 have been correctly entered into the Firebase console. 

Unfortunately this is a little tricky to debug, but hopefully this will give you a pointer in the right direction. Please let us know if these pointers helped.

**Comment by carlzimmerman** [comment]
It says in the dev console that use of this API scope will be restricted until it is approved.

**Comment by jfschmakeit** [comment]
We have just added a new "troubleshooting sign in" section to step 4 in the codelab. This should hopefully help if anyone gets stuck at this step.

If you have encountered any other issues at this step that aren't covered in this section, please do file a new issue and we can expand it.
Thanks!
